type Room {
    id: ID!
    name: String!
    size: Int!
}

input RoomInput {
    name: String!
    size: Int!
}

type Query {
    getRoomById(id: ID!): Room!
    getAllRooms: [Room!]!
}

type Mutation{
    createRoom(input: RoomInput!): Room!
    updateRoom(id: ID!, input: RoomInput!): Room!
    deleteRoom(id: ID!): Boolean
}