type User {
    id: ID!
    first_name: String!
    last_name: String!
    age: INTEGER!
    email: String
}

input UserInput {
    first_name: String!
    last_name: String!
    age: INTEGER!
    email: String
}

type Query {
    getUserById(id: ID!): User!
    getAllUsers: [User!]!
}

type Mutation{
    createUser(input: UserInput!): User!
    updateUser(id: ID!, input: UserInput!): User!
    deleteUser(id: ID!): Boolean
}