scalar Date

type User {
    id: ID!
    first_name: String!
    last_name: String!
    age: Int!
    email: String!
    active: Boolean
    created_at: Date
    updated_at: Date
    removed_at: Date
}

input UserInput {
    first_name: String!
    last_name: String!
    age: Int!
    email: String!
    active: Boolean
}

input UserUpdateInput {
    first_name: String
    last_name: String,
    age: Int,
    email: String
}

type Query {
    getUserById(id: ID!): User!
    getAllUsers(active: Boolean!): [User!]!
}

type Mutation{
    createUser(Active: Boolean!): User!
    updateUser(id: ID!, input: UserUpdateInput): User!
    deleteUser(id: ID!): Boolean!
}