type Post {
  id: String!
  user_id: String!
  title: String!
  content: String!
  created_at: Date
  updated_at: Date
  removed_at: Date
  user: User!
  post_messages: [Message]
  post_likes: [Likes]
}

input PostInput {
  user_id: String!
  title: String!
  content: String!
}

input PostUpdateInput {
  title: String
  content: String
}

type Query {
  getPostById(id: String!): Post!
  getAllPosts: [Post!]!
}

type Mutation {
  createPost(input: PostInput!): Post!
  updatePost(id: String!, input: PostUpdateInput!): Post!
  deletePost(id: String!): Boolean!
}
