type Topic {
    id: ID!
    name: String!
    theme: String!
    totalCount: Int!
    description: String!
    created_at: Date
    updated_at: Date
    removed_at: Date
}

input TopicInput {
    name: String!
    theme: String!
    description: String
    totalCount: Int
}

type Query {
    getTopicById(id: ID!): Topic
    getAllTopics(active: Boolean): [Topic!]!
}

type Mutation {
    createTopic(input: TopicInput!): Topic!
    updateTopic(id: ID!, input: TopicInput!): Topic!
    deleteTopic(id: ID!): Boolean!
}